#!/usr/bin/env bash
docker run \
    --name jupyter \
    --rm \
    -p 8888:8888 \
    -e GRANT_SUDO=yes \
    -e NB_USER=notebook \
    --volume $(realpath $(dirname "$0"))/notebook:/home/notebook \
    --user root \
    -w /home/notebook \
    -h jupyter \
    jupyter/qutip-notebook
